baseURL=https://www.amazon.in

#chrome | firefox | hub_chrome | hub_firefox
browser:chrome

mobile:FF4vsNV6twdgHoyqL3a/iMd6t6PbbULjHQQQL1faPuquG2lrkuA=
password:BGo/NYHffeC4PjYsVgJYxWgXDMR0xy0HyWXi04n+ED1yWHCx
name:virender kamboj